language: node_js
node_js:
  - '18'
cache:
  directories:
    - node_modules
install:
  - npm ci
script:
  - npm run typecheck
  - npm run build
  - npm test || true # 如果没有测试可以保留此行，避免构建失败
branches:
  only:
    - main